version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data --console-address ":9001"
    networks:
      - traefik_public
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: gersonortiz693
      MINIO_ROOT_PASSWORD: f79be0f54d7fc7e6335ad869d0cb2380
      MINIO_BROWSER_REDIRECT_URL: https://ssminiofrontss.s-team-marketing.com
      MINIO_SERVER_URL: https://ssminiobackss.s-team-marketing.com
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
          limits:
            cpus: '0.5'
            memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio_s3.rule=Host(`ssminiobackss.s-team-marketing.com`)
        - traefik.http.routers.minio_s3.tls.certresolver=le
        - traefik.http.routers.minio_s3.entrypoints=websecure
        - traefik.http.routers.minio_s3.tls=true
        - traefik.http.routers.minio_s3.service=minio_s3
        - traefik.http.services.minio_s3.loadbalancer.server.port=9000
        - traefik.http.routers.minio_console.rule=Host(`ssminiofrontss.s-team-marketing.com`)
        - traefik.http.routers.minio_console.tls.certresolver=le
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls=true
        - traefik.http.routers.minio_console.service=minio_console
        - traefik.http.services.minio_console.loadbalancer.server.port=9001

volumes:
  minio_data:
    external: true

networks:
  traefik_public:
    external: true
